# Generated by Django 3.2.7 on 2021-11-30 03:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('biography', models.CharField(max_length=250)),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(13)])),
                ('name', models.CharField(max_length=75)),
                ('publisher', models.CharField(max_length=75)),
                ('price', models.IntegerField()),
                ('genre', models.CharField(choices=[('FICTION', 'Fiction'), ('NONFICTION', 'Nonfiction'), ('DRAMA', 'Drama'), ('FOLKTALE', 'Folktale'), ('POETRY', 'Poetry')], max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('yearPublished', models.IntegerField()),
                ('copiesSold', models.IntegerField()),
                ('bookAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeekText.author')),
            ],
        ),
    ]
