# Generated by Django 3.2.8 on 2021-12-01 16:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeekText', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('emailAddress', models.CharField(blank=True, max_length=50, unique=True)),
                ('homeAddress', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(999999999999), django.core.validators.MaxValueValidator(9999999999999)]),
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GeekText.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GeekText.userprofile')),
            ],
        ),
    ]
