# Generated by Django 3.2.7 on 2021-11-24 01:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('biography', models.CharField(max_length=250)),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('publisher', models.CharField(max_length=75)),
                ('price', models.IntegerField()),
                ('genre', models.CharField(choices=[('FICTION', 'Fiction'), ('NONFICTION', 'Nonfiction'), ('DRAMA', 'Drama'), ('FOLKTALE', 'Folktale'), ('POETRY', 'Poetry')], max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('yearPublished', models.IntegerField()),
                ('copiesSold', models.IntegerField()),
                ('bookAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeekText.author')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeekText.book')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('emailAddress', models.CharField(blank=True, max_length=50, unique=True)),
                ('homeAddress', models.CharField(blank=True, max_length=100)),
                ('shoppingCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeekText.shoppingcart')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishListName', models.CharField(default='Null', max_length=100)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeekText.book')),
                ('user', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='GeekText.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('creditCardNumber', models.IntegerField()),
                ('ccType', models.CharField(max_length=30)),
                ('ccExpire', models.DateField()),
                ('ccSecurityCode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeekText.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numberOfStars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.CharField(default='', max_length=250)),
                ('date', models.DateField()),
                ('book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GeekText.book')),
            ],
        ),
    ]
