# Generated by Django 3.2.7 on 2021-10-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeekText', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
