# Generated by Django 3.2.8 on 2021-11-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeekText', '0003_alter_rating_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': (['-numberOfstars'],)},
        ),
        migrations.AddField(
            model_name='rating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews'),
        ),
        migrations.AddField(
            model_name='rating',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
