# Generated by Django 3.2.8 on 2021-11-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeekText', '0005_auto_20211101_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews'),
        ),
    ]
