# Generated by Django 3.2.9 on 2021-11-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeekText', '0007_alter_rating_numberofstars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='numberOfStars',
            field=models.IntegerField(choices=[('2', '2'), ('5', '5'), ('1', '1'), ('3', '3'), ('4', '4')], default='1'),
        ),
    ]
