# Generated by Django 3.2.9 on 2021-11-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeekText', '0009_auto_20211102_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='numberOfStars',
            field=models.IntegerField(choices=[('5', '5'), ('4', '4'), ('1', '1'), ('2', '2'), ('3', '3')], default='1'),
        ),
    ]
