# Generated by Django 3.2.9 on 2021-11-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeekText', '0010_alter_rating_numberofstars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='numberOfStars',
            field=models.IntegerField(choices=[('3', '3'), ('5', '5'), ('2', '2'), ('1', '1'), ('4', '4')], default='1'),
        ),
    ]
