# Generated by Django 3.2.9 on 2021-11-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeekText', '0012_auto_20211102_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
        migrations.AlterField(
            model_name='rating',
            name='numberOfStars',
            field=models.IntegerField(choices=[('4', '4'), ('3', '3'), ('1', '1'), ('5', '5'), ('2', '2')], default=''),
        ),
    ]
